= Conclusiones
Como hemos podido comprobar en la sección de _Evaluación de rendimiento y energía_, las optimizaciones realizadas han conseguido mejorar notablemente el rendimiento de nuestro proyecto. De hecho, como ya se ha mencionado, nuestros resultados de tiempo de ejecución son notablemente inferiores a los presentados como referencia en la plataforma _Aula Global_. Y ya no solo eso, también presentamos unos resultados de consumo energético y rendimiento que, para el crecimiento de objetos a renderizar crece de forma controlada y lineal, lo cual es algo que demuestra la positividad de los efectos de nuestras optimizaciones, como ya se ha mencionado en secciones anteriores de la memoria.

Por otro lado, en cuanto a la arquitectura de nuestro software, hemos podido realizar una división correcta entre las secciones de código que corresponden al modelo _AOS_ al _SOA_ y a aquellos ficheros comunes entre ambos modelos. Esto ha sido un aspecto clave en la realización de nuestro proyecto, ya no solo porque nos ha permitido dividir el trabajo de una manera más eficiente y organizada que nos ha permitido trabajar en paralelo para poder llegar a las fechas requeridas, sino también porque nos ha permitido aplicar las optimizaciones de una manera verdaderamente sencilla. Es más, nuestra división de las secciones comunes y las específicas (explicadas en mayor profundidad en la seción de _Diseño_) nos ha permitido evitar el código duplicado, que ha resultado también en permitir que cualquier optimización o cambio se aplicase tanto al modelo _AOS_ como al _SOA_ de manera efectiva sin necesidad de duplicar código. 

En relación con esto, consideramos realmente que este trabajo no solo nos ha planteado retos en relación con la _Arquitectura de Computadores_, ayudandonos a comprender mejor los conceptos vistos en clase, los métodos de optimización y los aspectos relacionados con el análisis de rendimiento y consumo energético y la realización de conclusiones pertintentes. El trabajo, además nos ha presentado retos a nivel _Arquitecura del Software_ lo que nosha permitido mejorar nuestras capacidades de organización de diseño, de trabajo conjunto para el desarrollo de software y el entendimiento de un lenguaje de programación con el que no habiamos tenido un extenso contacto previo, como es _C++_.

Por otro lado, el trabajo nos ha permitido conectar con mecanismos de optimización que se usan en industrias como es la del desarrollo de videojuegos. Precisamente en nuestro caso, una de las principales optimizaciones presentadas en nuestro código es la implementación de _Axis Aligned Bounding Boxes (AABB)_, una técnica que se utiliza de manera extensa en la industria de los videojuegos para permitir la mejora de rendimiento de las intersecciones entre rayos y entre elementos dentro de las escenas. odemos entender perfectamente el uso de dicho modelo pues hemos comprobado la eficacia que este supone para la mejora del rendimiento en nuestro proyecto concreto. Ya no solo eso, además nos ha permitido presentar unos resultados completamente escalables, pues sus efectos en la medida de rendimiento y consumo, como se ha visto en el comienzo de la sección de _Evalucación del Rendimiento_ nos permite comprobar que la optimización es aún más efectiva cuando el número de elementos que interviene en la escena es mayor. Consideramos, que la escalabilidad es una característica fundamental que se debe tener en mente en cualquier diseño software, y en este caso, hemos conseguido encontrar mecanismos que nos permiten garantizarla. 

Por otro lado, pese a no haber podido sacar unas conclusiones definitivasen relación con la diferencia de rendimiento en nuestro proyecto dependiendo del uso de _AOS_ o _SOA_, pues el efecto de nuestras optimizaciones ha conseguido que la diferencia sea practicamente despreciable, consideramos que la práctica nos ha sido completamente util para comprender mejor el funcionamiento de ambos modelos y sus aplicaciones en cuanto a código se refiere. Además, hemos podido trabajar en base a la trasformación de un modelo al otro, pues, de manera general, aplicabamos nuestros cambios únicamente en uno de los dos modelos indistintamente, y una vez probabamos la eficacia y correcto funcionamiento de los cambios, lo traduciamos al modelo contrario. Esto también nos ha permitido comprender mejor las diferencias entre ambos y mejorar nuestra capacidad de modificación y adaptación del código. 

Además, durante la realización del proyecto nos hemos enfrentado a numerosos problemas y retos. Entre estos retos, el primero de todos fue la optimización del código relacionado con los cilindros. Como se ha mencionado en secciones anteriores, e códgio relaccionado con las intersecciones y generaciones de rayos en cilindros suponía más de un 67% del código en nuestraversión inicial. Para nosotros, eso fue un reto verdaderamente importante, pues la primera solución encontrada, el precalculo de los valores relaccionados, nos proporcionó una soluciónefectiva, pero nos abrió las puertas a lagestión de meoria caché, una cuestión completamente nueva para nsostros. No osbtante, gracias a ello, conseguimos también relaccionar los conceptos vistos en clase acerca de la misma a nuestra práctoca y profundizar más en la relación entre la práctica y el contenido teórico que estudiamos en clase. Por otro lado, otro de los mayores retos a los que nos enfrentamos fue la resolución de _bugs_ en el código, especialmente dos: el correcto funcionamiento de los cilindros, pues estos nos presentaban unas extrañas manchas negras a las que no conseguíamos encontrarexplicación, y también el correcto funcionamiento de la lógica relaccionada con los materiales refractivos. Estos dos _bugs_ nos presentaron un verdadero reto, y realmente ocuparon una parteimportante del tiempo dedicado al proyecto, pricipalmentedurante las últimas dos semanas de trabajo. No obstante, el enfrentamieto a dichos problemas nos ha permitido adquirir conocimientos, que aunque no parecen directamente relaccionados con la asignatura, nos permiten adquirir competencias que relmente están relaccionadas con el mundo laboral. Entre ellas, la revisión de código de compañeros, pues en la mayoría de las ocasiones, la búsqueda del problema o solución en el código la realizabamos sobre el código realizado por nuestros compañeros, para mediante un enfoque nuevo, conseguir soluciones efectivas. EN ese mismo sentido, la práctica nos ha permitido mejorar nuestras capacidades de uso de herramientas de IA Generativa, principalmente para a depuraciń de código, lo cual consideramos es una competencia que será de gran utilidad en el fturo laboral próximo dada la creciente importancia de estas herramientas. 

En definitiva, consideramos que la realización de este proyecto ha sido muy positiva para nuestro aprendizaje, no solo en relación a los contenidos de la asignatura, también en relación a aspectos relaccionados con nuestro futuro laboral y con la funciones cotidianas de los ingenieros informáticos. Para nosotros, eso es algo que se valora muy positivamente y consideramos por ello que la práctica nos ha sido de verdadera utilidad. Además consideramos que el trabajo ha sido completamente satisfactorio, obteniendo uns resultados de rendimiento y consumo energético bastante buenosy adquiriendo conocimientos verdaderamente variados y útiles para nuestro futuro.
