= Conclusiones
En definitiva, consideramos que los resultados de la práctica han sido muy satisfactorios, presentando un speedup superior a 40 en la escena 5 y con un tiempo de ejecución aproximado de 1,8 segundos frente a los 175 que se presentan como valor máximo de referencia, lo que supone un tiempo casi 100 veces menor. 

Más allá de los resultados obtenidos, consideramos que la práctica ha sido muy util para nuestra formación en el contexto de la programación paralela, y más específicamente en el empleo de la librería TBB. En nuestro caso, nunca habíamos realizado programación paralela y poder aplicar los conocimientos adquiridos a un proyecto práctico, nos ha resultado muy interesante y útil. 

La práctica además nos ha ayudado a desarrollar mejores cualidades de análisis de rendimiento, comparativa de ejecuciones y organización de pruebas. En comparación con la primera entrega, el volumen de trabajo de evaluación y pruebas ha sido notoriamente superior, por lo que hemos tenido que desarrollar una estrategia más sofisticada y organizada de lo que lo hicimos en la primera entrega. 

En cuanto a aspectos a mejorar para futuros proyectos, destacamos el empleo de una mejor organización. En este caso, y pese a seguir una organización similar a la de la primera práctica, el tiempo se nos ha echado más encima. Nos habría gustado poder realizar alguna prueba más de evaluación para contrastar los resultados obtenidos, no obstante, dado que el tiempo de ejecución del trabajo era muy limitado y que esto ha conllevado la saturación del sistema _Avignon_, nos ha resultado algo complicado la realización de las mismas. 

En este caso, dado que la carga de programación era notoriamente inferior a la de la primera práctica, nuestras dificultades en ese ámbito han sido prácticamente inexistentes. EL único aspecto que nos ha dificultado ligeramente el trabajo (a parte de las esperas para ejecución y pruebas) ha sido la evaluación de los fragmentos de manera independiente. Dado que analizábamos cada fragmento de manera independiente, al combinar todos los resultados obtenidos y las combinaciones óptimas, sufrimos de problemas de _merge_ para las ramas que habíamos generado para la evaluación. Por ello, si tuviéramos que empezar de nuevo el proyecto, organizaríamos el trabajo de evaluación de una manera más secuencial en la que pudiéramos juntar los resultado obtenidos sin tantos problemas y conflictos. 

No obstante, estamos satisfechos con el trabajo realizado, con la organización como equipo de trabajo y consideramos que la práctica ha sido interesante y nos ha obtenido beneficios notorios no solo desde los conocimientos de la asignatura, también como programadores y estudiantes de ingeniería informática. 
