= Optimización
== Precálculo de operaciones en los cilindros.
Tras as primeras pruebas de rendimiento de nuestro programa, pudimos observar que un gran porcentaje del tiempo dedicado a la ejecución estaba concentrada en torno a la renderización de los cilindros (abarcando $~67\%$ de las instrucciones ejecutadas), por tanto, la gran mayoría de nuestros primeros esfuerzos fue a optimizar el renderizado de cilindros. 

Así, la primera solución encontrada fue precalcular las operaciones con un coste computacional elevado que se realizaban durante las intersecciones y generaciones de rayos con las diferentes partes de los cilindros (raíces cuadradas etc.). De este modo, conseguimos una reducción significativa en el número de veces que se realizaban dichas operaciones, y por tanto una reducción significativa en el tiempo de ejecución del programa. No obstante, esto también nos presento inconvenientes y nuevos conceptos en los que profundizar, como es la gestión de la memoria caché. Pese a no presentar un problema muy amplio en nuestro código, fue una cuestión a tener en cuenta de cara a las siguientes optimizaciones, pues dado que ya habíamos realizado un precálculo de las operaciones más costosas en los cilindros, nos abstenimos de realizarlas en otras secciones de nuestro proyecto dado que podría generar fallos de memoria caché y por tanto, una pérdida de rendimiento mayor a la que genera el cálculo que pretendíamos optimizar.
== Axis-Aligned Bounding Box. (AABB)
También se ha planteado un modelo AABB (Axis-Aligned Bounding Box), cuyo uso es muy frecuente en el renderizado de videojuegos. El método consiste en introducir los elementos gráficos en una "caja" tridimensional alineada con los ejes de coordenadas. Dicha caja se utiliza para realizar una primera aproximación de las colisiones entre rayos, en caso de que el rayo se introduzca en el espacio delimitado por la caja, se comprueba si realmente el rayo colisiona con el objeto, en caso contrario, no se calcula la intersección. 

Esto resulta eficiente ya que el cálculo de intersecciones de los rayos con los las esferas, y especialmente con los cilindros, requieren numerosas operaciones con un coste computacional bastante elevado como ya se ha mencionado en el apartado anterior. Sin embargo, las intersecciones con la caja que envuelve los objetos, dadas sus características y su condición alineada con los ejes de coordenadas, requieren operaciones con un coste computacional muy reducido (mayoritariamente sumas). Por tanto, pese a requerir una comprobación previa que puede generar una pequeña perdida de rendimiento en los casos en los que los rayos si impacten con los objetos, en la gran mayoría de los casos, se evita realizar las operaciones con un coste más elevado ya que se descarta la posibilidad de intersección con las operaciones más sencillas de la caja AABB que rodea los elementos, haciendo que el rendimiento general del programa mejore notoriamente. Además es un modelo que presenta una muy buena escalabilidad, pues sus efectos, como ya se demostrará en apartados posteriores del documento, tiene un mayor efecto en el rendimiento cuantos más elementos gráficos haya en la escena.
== Modificación de flags.

