#!/bin/bash
# Script para ejecutar todas las pruebas de rendimiento y energía generadas.

set -Eeuo pipefail

echo "================================================="
echo "INICIANDO BANCO DE PRUEBAS DE RENDIMIENTO Y ENERGÍA"
echo "================================================="

# Ejecutar todas las pruebas una por una
    bash "tests_de_config/01_profundidad_rayos/test_profundidad_5.sh"
    bash "tests_de_config/01_profundidad_rayos/test_profundidad_10.sh"
    bash "tests_de_config/01_profundidad_rayos/test_profundidad_20.sh"
    bash "tests_de_config/01_profundidad_rayos/test_profundidad_50.sh"
    bash "tests_de_config/01_profundidad_rayos/test_profundidad_100.sh"
    bash "tests_de_config/01_profundidad_rayos/test_profundidad_200.sh"
    bash "tests_de_config/02_samples_per_pixel/test_samples_3.sh"
    bash "tests_de_config/02_samples_per_pixel/test_samples_5.sh"
    bash "tests_de_config/02_samples_per_pixel/test_samples_15.sh"
    bash "tests_de_config/02_samples_per_pixel/test_samples_30.sh"
    bash "tests_de_config/02_samples_per_pixel/test_samples_50.sh"
    bash "tests_de_config/02_samples_per_pixel/test_samples_150.sh"
    bash "tests_de_config/03_ancho_imagen/test_ancho_270.sh"
    bash "tests_de_config/03_ancho_imagen/test_ancho_720.sh"
    bash "tests_de_config/03_ancho_imagen/test_ancho_1280.sh"
    bash "tests_de_config/03_ancho_imagen/test_ancho_1920.sh"
    bash "tests_de_config/03_ancho_imagen/test_ancho_2340.sh"
    bash "tests_de_config/03_ancho_imagen/test_ancho_3840.sh"
    bash "tests_de_escenas/01_matte_esfera/test_1_obj.sh"
    bash "tests_de_escenas/01_matte_esfera/test_2_obj.sh"
    bash "tests_de_escenas/01_matte_esfera/test_4_obj.sh"
    bash "tests_de_escenas/01_matte_esfera/test_8_obj.sh"
    bash "tests_de_escenas/01_matte_esfera/test_16_obj.sh"
    bash "tests_de_escenas/01_matte_esfera/test_32_obj.sh"
    bash "tests_de_escenas/01_matte_esfera/test_128_obj.sh"
    bash "tests_de_escenas/01_matte_esfera/test_256_obj.sh"
    bash "tests_de_escenas/02_matte_cilindro/test_1_obj.sh"
    bash "tests_de_escenas/02_matte_cilindro/test_2_obj.sh"
    bash "tests_de_escenas/02_matte_cilindro/test_4_obj.sh"
    bash "tests_de_escenas/02_matte_cilindro/test_8_obj.sh"
    bash "tests_de_escenas/02_matte_cilindro/test_16_obj.sh"
    bash "tests_de_escenas/02_matte_cilindro/test_32_obj.sh"
    bash "tests_de_escenas/02_matte_cilindro/test_128_obj.sh"
    bash "tests_de_escenas/02_matte_cilindro/test_256_obj.sh"
    bash "tests_de_escenas/03_metal_esfera/test_1_obj.sh"
    bash "tests_de_escenas/03_metal_esfera/test_2_obj.sh"
    bash "tests_de_escenas/03_metal_esfera/test_4_obj.sh"
    bash "tests_de_escenas/03_metal_esfera/test_8_obj.sh"
    bash "tests_de_escenas/03_metal_esfera/test_16_obj.sh"
    bash "tests_de_escenas/03_metal_esfera/test_32_obj.sh"
    bash "tests_de_escenas/03_metal_esfera/test_128_obj.sh"
    bash "tests_de_escenas/03_metal_esfera/test_256_obj.sh"
    bash "tests_de_escenas/04_metal_cilindro/test_1_obj.sh"
    bash "tests_de_escenas/04_metal_cilindro/test_2_obj.sh"
    bash "tests_de_escenas/04_metal_cilindro/test_4_obj.sh"
    bash "tests_de_escenas/04_metal_cilindro/test_8_obj.sh"
    bash "tests_de_escenas/04_metal_cilindro/test_16_obj.sh"
    bash "tests_de_escenas/04_metal_cilindro/test_32_obj.sh"
    bash "tests_de_escenas/04_metal_cilindro/test_128_obj.sh"
    bash "tests_de_escenas/04_metal_cilindro/test_256_obj.sh"
    bash "tests_de_escenas/05_refractivo_esfera/test_1_obj.sh"
    bash "tests_de_escenas/05_refractivo_esfera/test_2_obj.sh"
    bash "tests_de_escenas/05_refractivo_esfera/test_4_obj.sh"
    bash "tests_de_escenas/05_refractivo_esfera/test_8_obj.sh"
    bash "tests_de_escenas/05_refractivo_esfera/test_16_obj.sh"
    bash "tests_de_escenas/05_refractivo_esfera/test_32_obj.sh"
    bash "tests_de_escenas/05_refractivo_esfera/test_128_obj.sh"
    bash "tests_de_escenas/05_refractivo_esfera/test_256_obj.sh"
    bash "tests_de_escenas/06_refractivo_cilindro/test_1_obj.sh"
    bash "tests_de_escenas/06_refractivo_cilindro/test_2_obj.sh"
    bash "tests_de_escenas/06_refractivo_cilindro/test_4_obj.sh"
    bash "tests_de_escenas/06_refractivo_cilindro/test_8_obj.sh"
    bash "tests_de_escenas/06_refractivo_cilindro/test_16_obj.sh"
    bash "tests_de_escenas/06_refractivo_cilindro/test_32_obj.sh"
    bash "tests_de_escenas/06_refractivo_cilindro/test_128_obj.sh"
    bash "tests_de_escenas/06_refractivo_cilindro/test_256_obj.sh"

echo "================================================="
echo "BANCO DE PRUEBAS FINALIZADO"
echo "================================================="
